name: Update resources

on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 0

permissions:
  contents: write
  pull-requests: write

jobs:
  update-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
      - name: Update resources
        run: npm run update:resources
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "fix: updates resources"
          branch: update-resource
          branch-suffix: timestamp
          title: "fix: updates resources"
